version: "3.8"

services:
  frontend:
    build: ./frontend
    container_name: rn_frontend
    ports:
      - "8081:8081"        # Metro
      - "19000:19000"      # Expo DevTools / bundle
      - "19000:19000/udp"  # Expo LAN discovery (optional)
      - "19001:19001"      # Expo (legacy websocket/debug)
      - "19002:19002"      # Expo web UI (legacy)
    environment:
      NODE_ENV: development
      REACT_NATIVE_PACKAGER_HOSTNAME: "192.168.x.x"  # <-- your host LAN IP
      # CHOKIDAR_USEPOLLING: "true"  # if hot-reload misses changes on Windows
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    # no depends_on, no backend

volumes:
  node_modules:
